print('60/bpm*4/duration')
print('введите bpm и duration:')
print('bpm:(0-∞)')
bpm=int(input())
print('duration:(1-𝅝;2-𝅗𝅥;4-𝅘𝅥;8-𝅘𝅥𝅮;16-𝅘𝅥𝅯;32-𝅘𝅥𝅰;64-𝅘𝅥𝅱;128-𝅘𝅥𝅲)')
duration=int(input())
print(bpm)
print(duration)
print('длительность в секундах:')
print(60/bpm*4/duration)
